// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCSXi0TYSAHUUyWuKOdMatEflpsygf3aE',
    appId: '1:626894407906:web:43ace9f5a9fc7b61c036bb',
    messagingSenderId: '626894407906',
    projectId: 'fir-news-app-652cc',
    authDomain: 'fir-news-app-652cc.firebaseapp.com',
    storageBucket: 'fir-news-app-652cc.appspot.com',
    measurementId: 'G-ZPJ2XBY649',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqh1sC5SK_Gwf3IFMHyY4eNkQNQx-asd4',
    appId: '1:626894407906:android:01707855b38f1469c036bb',
    messagingSenderId: '626894407906',
    projectId: 'fir-news-app-652cc',
    storageBucket: 'fir-news-app-652cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdw67OK7wkY5vFpXMLaTPPVfsYcdBsOs',
    appId: '1:626894407906:ios:5a5a7b19f95bedffc036bb',
    messagingSenderId: '626894407906',
    projectId: 'fir-news-app-652cc',
    storageBucket: 'fir-news-app-652cc.appspot.com',
    iosBundleId: 'com.example.firebaseNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjdw67OK7wkY5vFpXMLaTPPVfsYcdBsOs',
    appId: '1:626894407906:ios:5a5a7b19f95bedffc036bb',
    messagingSenderId: '626894407906',
    projectId: 'fir-news-app-652cc',
    storageBucket: 'fir-news-app-652cc.appspot.com',
    iosBundleId: 'com.example.firebaseNewsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCSXi0TYSAHUUyWuKOdMatEflpsygf3aE',
    appId: '1:626894407906:web:c775e2b0e4ba6884c036bb',
    messagingSenderId: '626894407906',
    projectId: 'fir-news-app-652cc',
    authDomain: 'fir-news-app-652cc.firebaseapp.com',
    storageBucket: 'fir-news-app-652cc.appspot.com',
    measurementId: 'G-XTS98GZL17',
  );
}
